LoL-pj/LoL-VC

- app/views/layouts/application.html.erb
- config/routes.rb
- config/webpacker.yml
**内容**
投稿フォーム作成にあたり、viewを作成しました
> teams#indexのviewを作成

- Dockerfile
- config/database.yml
- docker-compose.yml
- entrypoint.sh
closed #5 
**内容**
Docker環境を作成しました
`docker-compose up`でサーバー起動できます👍
> Docker環境の構築

- app/models/champion.rb
- app/models/game_type.rb
- app/models/rank.rb
- app/models/tag.rb
- app/models/team.rb
- app/models/team_champion.rb
- app/models/team_game_type.rb
- app/models/team_rank.rb
- app/models/team_tag.rb
- db/migrate/20200402124207_create_game_types.rb
- db/migrate/20200402130011_create_teams.rb
- db/migrate/20200402132146_create_team_champions.rb
- db/migrate/20200425134356_create_team_ranks.rb
- db/migrate/20200425140852_create_team_game_types.rb
- db/schema.rb
- test/fixtures/game_types.yml
- test/fixtures/team_game_types.yml
- test/fixtures/team_ranks.yml
- test/models/game_type_test.rb
- test/models/team_game_type_test.rb
- test/models/team_rank_test.rb
- それぞれのアソシエーションをモデル内で組んだ。
- game_typesモデルを作成し、それに伴い中間テーブルteam_game_typesを作成
- ranksの中間テーブルteam_ranksの追加
> Create associatiton and game_types model

- app/views/teams/_teams.html.haml
closed #4
**内容**
サモナー名をクリック後opggへジャンプするように変更した
> サモナー名からopggへジャンプする

- Makefile
自分用にMakefileを作成しました。README.mdに書いてあるDockerコマンドがMakefileで使えるようになっています。
例えば、`docker-compose build`でアプリケーションをビルドさせる場合は、下記のコマンドを打ちます。
```
$ make build
```
アプリケーションを起動させる場合は、下記のコマンドを打ちます。
```
$ make start
```
> Add: Makefile

- app/views/teams/_teams.html.haml
> 🐛Fix update ddragon version

- README.md
READMEの更新
API KEYを.envファイルで管理するようにした
> ✨Update setting .env

- app/controllers/teams_controller.rb
- app/models/lane.rb
- app/models/team.rb
- app/models/team_lane.rb
- app/views/teams/_form.html.haml
- app/views/teams/_search.html.haml
- app/views/teams/_teams.html.haml
- app/views/teams/show.html.haml
- db/migrate/20200830164235_create_lanes.rb
- db/migrate/20200830164945_create_team_lanes.rb
- db/schema.rb
- db/seeds.rb
- test/fixtures/lanes.yml
- test/fixtures/team_lanes.yml
- test/models/lane_test.rb
- test/models/team_lane_test.rb
> ✨Add association and lanes model

- app/assets/stylesheets/teams.scss
- app/controllers/teams_controller.rb
- app/models/team.rb
- app/views/teams/_form.html.haml
- app/views/teams/_teams.html.haml
- app/views/teams/show.html.haml
- db/migrate/20200920041943_remove_title_from_teams.rb
- db/schema.rb
- test/fixtures/teams.yml
募集フォームでタイトルを入力する箇所があったが必要なさそうなので削除
多分フォームはシンプルにした方がいいいかも⭐️ϵ( 'Θ' )϶⭐️
> 🚿Delete title column

- app/assets/stylesheets/teams.scss
- app/views/layouts/application.html.haml
- app/views/teams/_teams.html.haml
- app/views/teams/index.html.haml
- app/views/teams/show.html.haml
- 募集ボタンの配置を変更
- 一番ユーザが目につく部分に変更
- カードのレイアウトを変更
- なるべく情報が多すぎないように
> Refactor Layout

- app/controllers/teams_controller.rb
- app/models/team.rb
- app/views/teams/_form.html.haml
- config/locales/views/teams/ja.yml
- db/migrate/20200929142939_add_gender_to_teams.rb
- db/schema.rb
Reverts LoL-pj/LoL-VC#66
本番環境で起こる新規投稿ページに対応する
> Revert "✨Add gender column"

- app/assets/stylesheets/teams.scss
- app/views/teams/_teams.html.haml
内容
genderが持つカラムによって投稿の色を変更した
man: blue
woman: red
unknown: gray
> ✨Update posts layout to gender

- app/controllers/teams_controller.rb
Fixes #74
Added your suggestion (order method)
> New posts have to come at the beginning

- app/assets/stylesheets/teams.scss
- app/views/teams/_teams.html.haml
Add the posting time in message.
You can see the time the user posted!
Changed image
> ✨Add post time in message

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feture_request.md
closed #
Create github template
@LeonTeraoka 
Please, see writing English.
> ✨Add github template

- app/views/teams/_teams.html.haml
Update version 10.21.1 for ddragon.
> ⬆️Update version for ddragon

- config/application.rb
closed #91 
Set the TimeZone of Team model updated_at column to JST.
https://iriya-0624.hatenadiary.org/entry/20130429/1367244830
> 🐛Fix timezone from UTC to JST

- app/assets/stylesheets/teams.scss
> changed font color

- app/assets/stylesheets/teams.scss
Do you think it looks pretty good than #75 ?
> Amend the gender color

- app/views/teams/_form.html.haml
Fixed the tag orders.
close #97
> Fixed the tag order

- app/controllers/teams_controller.rb
- app/views/teams/_form.html.haml
- app/views/teams/_teams.html.haml
- app/views/teams/show.html.haml
- db/seeds.rb
- 投稿フォーム（新規作成・編集）のチェックボックスからランク選択をなくす
- TOPページ・詳細ページのランクタグをAPIから取得したものだけにする
- Seedデータも更新
> 🚿Remove ranked checkbox in post form

- db/seeds.rb
#105 
Add WildRift to GameTypes with @LeonTeraoka is advice.🙂
> ✨Add WildRift to GameTypes in seed data

- app/views/layouts/application.html.haml
`meta.description` is explanation column under the site title displayed at the time of search
> ✨SEO measures

- app/views/layouts/application.html.haml
> Revert "✨SEO measures"

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/teams_controller.rb
- app/helpers/user_agent_helper.rb
- app/views/layouts/application.html.haml
- app/views/teams/_form.html+mobile.haml
- app/views/teams/_search.html+mobile.haml
- app/views/teams/_team.html+mobile.haml
- app/views/teams/edit.html+mobile.haml
- app/views/teams/index.html+mobile.haml
- app/views/teams/new.html+mobile.haml
- app/views/teams/search.html+mobile.haml
- app/views/teams/show.html+mobile.haml
closed #33
- Install gem `useragent`
https://github.com/gshutler/useragent
- Use ActionPack Variants for mobile support.
https://coderwall.com/p/etlnvg/how-to-use-rails-4-1-actionpack-variants
1. mobile view
```shell
6: def user_agent
=> 7:   binding.pry
8:   @user_agent ||= UserAgent.parse(user_agent_string)
9: end
[1] pry(#<TeamsController>)> UserAgent.parse(user_agent_string)
=> [#<UserAgent:0x00007febad3c02d0
@comment=["iPhone", "CPU iPhone OS 13_2_3 like Mac OS X"],
@product="Mozilla",
@version=#<UserAgent::Version 5.0>>,
#<UserAgent:0x00007febad3c7cb0
@comment=["KHTML, like Gecko"],
@product="AppleWebKit",
@version=#<UserAgent::Version 605.1.15>>,
#<UserAgent:0x00007febad3c7850
@comment=nil,
@product="Version",
@version=#<UserAgent::Version 13.0.3>>,
#<UserAgent:0x00007febad3c7468 …
```
> ✨Add ActionPack Variants

- app/models/team.rb
Summary
First, added begin to team.rb, line 73, and surrounded the places where errors are likely to occur with begin.
Next, added rescue to line 79 and add the processing of the place where the error occurred in rescue.
Result
You can now post without error even if the ID does not exist.
> fixed no method error

- app/assets/stylesheets/teams.scss
Summary 
1. Fixed the circle size for safari.
2.Flattened the position of the summoner ID and icon.
Result
The layout looks better than before.
fix#114
> fixed broken layout

- app/views/teams/show.html.haml
Summary
It turns out that the gender color is not reflected because there was no if statement in show.html.haml to handle the condition.
Result
The gender color will be reflected on the screen after posting.
> fixed gender color

- app/views/teams/show.html.haml
Summary
1.It turns out that the gender color is not reflected because there was no if statement in show.html.haml to handle the condition.
2.Fixed ddragon version
Result
The gender color will be reflected on the screen after posting.
> fixed show gender

- app/views/teams/show.html.haml
Summary
Removed line breaks to avoid errors.
Result
No error after posting.
> R fixed show gender

- app/assets/stylesheets/teams.scss
- config/environments/production.rb
Summary
Fixed padding 0 55px → padding 0 35px in teams.scss
Result
Adjust the position to a little bit left side of the card.
close #121
> Fixed the card position to left side

- app/assets/stylesheets/teams.scss
> Revert "Fixed the card position to left side"

- app/controllers/teams_controller.rb
- app/models/team.rb
- app/views/teams/_form.html+mobile.haml
- app/views/teams/_form.html.haml
- app/views/teams/_team.html+mobile.haml
- app/views/teams/_teams.html.haml
- db/migrate/20201229063842_add_hidden_to_teams.rb
- db/schema.rb
- spec/factories/teams.rb
- spec/models/team_spec.rb
- test/fixtures/teams.yml
- test/models/team_test.rb
Allows you to choose to show or hide ranks.
>  Allows you to choose to show or hide ranks

- app/assets/stylesheets/teams.scss
- app/views/teams/_form.html.haml
Summary
Adjust only the color of the message frame.
Result
The color of the frame is now the same as the other forms.
> Change the message color

- app/controllers/teams_controller.rb
- app/models/team.rb
・team.rb 
Defined the unknown summoner name & make it return if the data was unknown(true).
・teams_controller.rb
Added the alert.
The alert will appear if the summoner's name is unknown. 
close #139
> 存在しないサモナー名
